### ISSUE TITLE
Entrega de Actividades

### ISSUE THREAD

**Issue by dmarcela09** [udistrital/tesoreria_cliente#85]
Resumen de actividades para entrega:

1. Inversiones

- [x]  Maquetacion de mockups #16 (no funcional)
- [x]  Propuesta de modelo de datos

2. Información Exógena

- [x]  Maquetacion de mockups #42 (no funcional)
- [x]  Referencia a modelos de datos o apis existentes

3. Certificado de Retenciones

- [x]  Maquetacion de mockups #64  (no funcional)
- [x]  Referencia a modelos de datos o apis existentes

**Comment by dmarcela09** [comment]
Para la propuesta del modelo de datos de Inversiones:

![Inversiones-2021-04-14_19-01](https://user-images.githubusercontent.com/26507343/114898655-edea0b00-9dd7-11eb-867b-52bad46089ea.png)

Basado en los mockups de Inversiones #16

**Comment by dmarcela09** [comment]
Resumen de Informe de entrega [InformeEntrega.pdf](https://github.com/udistrital/tesoreria_cliente/files/6351843/InformeEntrega.pdf)

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
